class AmazonPrime
{
	public static void main(String[] prime)
	{
		String teluguMovies[]={"Cheekatilo","Uppu Kappurambu","Drive","JIGRIS","23 (Iravai Moodu)","Hathya","Kalki 2898 AD","Hit (The First Case)","Naari Naari Naduma Murari","V","Maharshi","F2 - Fun and Frustration","Whistle","Evaru","28 Degree Celsius","Game Changer","Chaurya Paatham","Saaho","Pushpa: The Rise","HIT: The Second Case","Acharya","Yashoda","Ee Nagaraniki Emaindi","Guvva Gorinka","NOTA","Radhe Shyam","Vakeel Saab","Sarkaru Vaari Paata","Goodachari","Majili"};
		String kannadaMovies[]={"Dia","Rathnan Prapancha","Law","One Cut Two Cut","Ikkat","French Biriyani","K.G.F: Chapter 1","K.G.F: Chapter 2","Gantumoote","Love Mocktail","Avane Srimannarayana","Kavalu Daari","Rathaavara","Nanna Prakara","Katheyondu Shuruvagide","777 Charlie","Pailwaan","Bell Bottom","Yuvarathnaa","Kantara","Roberrt","Raajakumara","James","Ugramm","Mufti","Tagaru","Kirrak Party","Ondu Motteya Kathe","Simple Agi Ondh Love Story","Godhi Banna Sadharana Mykattu"};
		String tamilMovies[]={"Anbe Sivam","Nayakan","Pariyerum Perumal","Thevar Magan","Saani Kaayidham","Mahaan","Udanpirappe","Raame Aandalum Raavane Aandalum","Soorarai Pottru","Saani Kaayidham","Vikram Vedha","Saani Kaayidham","96","Bheemaa","Alaipayuthey","Kodi","Kaala","Mouna Ragam","OK Kanmani","Putham Pudhu Kaalai","Thadam","Uriyadi","Vellai Pookal","Seethakaathi","Manmadhan","Annamalai","Bombay","Vikram","Saani Kaayidham Redux","Thani Oruvan"};
		String malayalamMovies[]={"Drishyam","Drishyam 2","Aavesham","Golam","Pachuvum Athbutha Vilakkum","Ittymaani: Made in China","Charles Enterprises","Pathinettam Padi","Cold Case","Ela Veezha Poonchira","Kooman","C U Soon","Joseph","Nizhal","Kumbalangi Nights","Joji","Ayyappanum Koshiyum","Kaathal – The Core","Bhramam","Sara's","Helen","Unda","Virus","Garudan","Malik","The Great Indian Kitchen","Android Kunjappan Version 5.25","Uyare","Thondimuthalum Driksakshiyum","Take Off"};
		String hindiMovies[]={"Shershaah","Sardar Udham","Maja Ma","Tiku Weds Sheru","Sharmajee Ki Beti","Ae Watan Mere Watan","Runway 34","Jug Jugg Jeeyo","Yeh Jawaani Hai Deewani","Barfi!","Raazi","The Lunchbox","Tumbbad","Stree","Section 375","Hindi Medium","Aashiqui 2","Raja Hindustani","Hum Dil De Chuke Sanam","Ajab Prem Ki Ghazab Kahani","Bachchhan Paandey","Unpaused","Toofaan","Gehraiyaan","Bhoot: Part One - The Haunted Ship","Fan","Satyameva Jayate","Coolie No. 1","Dil Bechara","Good Newwz"};
		String englishMovies[]={"The Shawshank Redemption","The Lord of the Rings: The Fellowship of the Ring","The Lord of the Rings: The Two Towers","The Lord of the Rings: The Return of the King","The Matrix","Inception","Interstellar","Gladiator","The Dark Knight","Titanic","Forrest Gump","The Prestige","Arrival","The Silence of the Lambs","The Social Network","Mad Max: Fury Road","The Wolf of Wall Street","A Quiet Place","The Tomorrow War","Mission: Impossible – Fallout","No Time to Die","Casino Royale","The Beekeeper","The Big Lebowski","La La Land","Ready Player One","Collateral","Fargo","Red, White & Royal Blue","Upgraded"};
		
		String cheekatilo=teluguMovies[0];
		System.out.println(cheekatilo);
		String uppuKappurambu=teluguMovies[1];
		System.out.println(uppuKappurambu);
		String drive=teluguMovies[2];
		System.out.println(drive);
		String jigris=teluguMovies[3];
		System.out.println(jigris);
		String iravaiMoodu=teluguMovies[4];
		System.out.println(iravaiMoodu);
		String hathya=teluguMovies[5];
		System.out.println(hathya);
		String kalki2898=teluguMovies[6];
		System.out.println(kalki2898);
		String hit1=teluguMovies[7];
		System.out.println(hit1);
		String naariNaari=teluguMovies[8];
		System.out.println(naariNaari);
		String vMovie=teluguMovies[9];
		System.out.println(vMovie);
		String maharshi=teluguMovies[10];
		System.out.println(maharshi);
		String f2=teluguMovies[11];
		System.out.println(f2);
		String whistle=teluguMovies[12];
		System.out.println(whistle);
		String evaru=teluguMovies[13];
		System.out.println(evaru);
		String twentyEightDegree=teluguMovies[14];
		System.out.println(twentyEightDegree);
		String gameChanger=teluguMovies[15];
		System.out.println(gameChanger);
		String chauryaPaatham=teluguMovies[16];
		System.out.println(chauryaPaatham);
		String saaho=teluguMovies[17];
		System.out.println(saaho);
		String pushpaRise=teluguMovies[18];
		System.out.println(pushpaRise);
		String hit2=teluguMovies[19];
		System.out.println(hit2);
		String acharya=teluguMovies[20];
		System.out.println(acharya);
		String yashoda=teluguMovies[21];
		System.out.println(yashoda);
		String eeNagaraniki=teluguMovies[22];
		System.out.println(eeNagaraniki);
		String guvvaGorinka=teluguMovies[23];
		System.out.println(guvvaGorinka);
		String nota=teluguMovies[24];
		System.out.println(nota);
		String radheShyam=teluguMovies[25];
		System.out.println(radheShyam);
		String vakeelSaab=teluguMovies[26];
		System.out.println(vakeelSaab);
		String sarkaruVaariPaata=teluguMovies[27];
		System.out.println(sarkaruVaariPaata);
		String goodachari=teluguMovies[28];
		System.out.println(goodachari);
		String majili=teluguMovies[29];
		System.out.println(majili);
				
		
		String dia=kannadaMovies[0];
		System.out.println(dia);
		String rathnanPrapancha=kannadaMovies[1];
		System.out.println(rathnanPrapancha);
		String law=kannadaMovies[2];
		System.out.println(law);
		String oneCutTwoCut=kannadaMovies[3];
		System.out.println(oneCutTwoCut);
		String ikkat=kannadaMovies[4];
		System.out.println(ikkat);
		String frenchBiriyani=kannadaMovies[5];
		System.out.println(frenchBiriyani);
		String kgf1=kannadaMovies[6];
		System.out.println(kgf1);
		String kgfChapter2=kannadaMovies[7];
		System.out.println(kgfChapter2);
		String gantumoote=kannadaMovies[8];
		System.out.println(gantumoote);
		String loveMocktail=kannadaMovies[9];
		System.out.println(loveMocktail);
		String avaneSrimannarayana=kannadaMovies[10];
		System.out.println(avaneSrimannarayana);
		String kavaluDaari=kannadaMovies[11];
		System.out.println(kavaluDaari);
		String rathaavara=kannadaMovies[12];
		System.out.println(rathaavara);
		String nannaPrakara=kannadaMovies[13];
		System.out.println(nannaPrakara);
		String katheyonduShuruvagide=kannadaMovies[14];
		System.out.println(katheyonduShuruvagide);
		String sevenSevenSevenCharlie=kannadaMovies[15];
		System.out.println(sevenSevenSevenCharlie);
		String pailwaan=kannadaMovies[16];
		System.out.println(pailwaan);
		String bellBottom=kannadaMovies[17];
		System.out.println(bellBottom);
		String yuvarathnaa=kannadaMovies[18];
		System.out.println(yuvarathnaa);
		String kantara=kannadaMovies[19];
		System.out.println(kantara);
		String roberrt=kannadaMovies[20];
		System.out.println(roberrt);
		String raajakumara=kannadaMovies[21];
		System.out.println(raajakumara);
		String james=kannadaMovies[22];
		System.out.println(james);
		String ugramm=kannadaMovies[23];
		System.out.println(ugramm);
		String mufti=kannadaMovies[24];
		System.out.println(mufti);
		String tagaru=kannadaMovies[25];
		System.out.println(tagaru);
		String kirrakParty=kannadaMovies[26];
		System.out.println(kirrakParty);
		String onduMotteyaKathe=kannadaMovies[27];
		System.out.println(onduMotteyaKathe);
		String simpleAgiOndhLoveStory=kannadaMovies[28];
		System.out.println(simpleAgiOndhLoveStory);
		String godhiBanna=kannadaMovies[29];
		System.out.println(godhiBanna);

		
		String anbeSivam=tamilMovies[0];
		System.out.println(anbeSivam);
		String nayakan=tamilMovies[1];
		System.out.println(nayakan);
		String pariyerumPerumal=tamilMovies[2];
		System.out.println(pariyerumPerumal);
		String thevarMagan=tamilMovies[3];
		System.out.println(thevarMagan);
		String saaniKaayidham1=tamilMovies[4];
		System.out.println(saaniKaayidham1);
		String mahaan=tamilMovies[5];
		System.out.println(mahaan);
		String udanpirappe=tamilMovies[6];
		System.out.println(udanpirappe);
		String raameAandalum=tamilMovies[7];
		System.out.println(raameAandalum);
		String sooraraiPottru=tamilMovies[8];
		System.out.println(sooraraiPottru);
		String saaniKaayidham2=tamilMovies[9];
		System.out.println(saaniKaayidham2);
		String vikramVedha=tamilMovies[10];
		System.out.println(vikramVedha);
		String saaniKaayidham3=tamilMovies[11];
		System.out.println(saaniKaayidham3);
		String ninetySix=tamilMovies[12];
		System.out.println(ninetySix);
		String bheemaa=tamilMovies[13];
		System.out.println(bheemaa);
		String alaipayuthey=tamilMovies[14];
		System.out.println(alaipayuthey);
		String kodi=tamilMovies[15];
		System.out.println(kodi);
		String kaala=tamilMovies[16];
		System.out.println(kaala);
		String mounaRagam=tamilMovies[17];
		System.out.println(mounaRagam);
		String okKanmani=tamilMovies[18];
		System.out.println(okKanmani);
		String puthamPudhuKaalai=tamilMovies[19];
		System.out.println(puthamPudhuKaalai);
		String thadam=tamilMovies[20];
		System.out.println(thadam);
		String uriyadi=tamilMovies[21];
		System.out.println(uriyadi);
		String vellaiPookal=tamilMovies[22];
		System.out.println(vellaiPookal);
		String seethakaathi=tamilMovies[23];
		System.out.println(seethakaathi);
		String manmadhan=tamilMovies[24];
		System.out.println(manmadhan);
		String annamalai=tamilMovies[25];
		System.out.println(annamalai);
		String bombay=tamilMovies[26];
		System.out.println(bombay);
		String vikram=tamilMovies[27];
		System.out.println(vikram);
		String saaniKaayidhamRedux=tamilMovies[28];
		System.out.println(saaniKaayidhamRedux);
		String thaniOruvan=tamilMovies[29];
		System.out.println(thaniOruvan);

		

		String drishyam=malayalamMovies[0];
		System.out.println(drishyam);
		String drishyam2=malayalamMovies[1];
		System.out.println(drishyam2);
		String aavesham=malayalamMovies[2];
		System.out.println(aavesham);
		String golam=malayalamMovies[3];
		System.out.println(golam);
		String pachuvum=malayalamMovies[4];
		System.out.println(pachuvum);
		String ittymaani=malayalamMovies[5];
		System.out.println(ittymaani);
		String charlesEnterprises=malayalamMovies[6];
		System.out.println(charlesEnterprises);
		String pathinettamPadi=malayalamMovies[7];
		System.out.println(pathinettamPadi);
		String coldCase=malayalamMovies[8];
		System.out.println(coldCase);
		String elaVeezha=malayalamMovies[9];
		System.out.println(elaVeezha);
		String kooman=malayalamMovies[10];
		System.out.println(kooman);
		String cuSoon=malayalamMovies[11];
		System.out.println(cuSoon);
		String joseph=malayalamMovies[12];
		System.out.println(joseph);
		String nizhal=malayalamMovies[13];
		System.out.println(nizhal);
		String kumbalangiNights=malayalamMovies[14];
		System.out.println(kumbalangiNights);
		String joji=malayalamMovies[15];
		System.out.println(joji);
		String ayyappanumKoshiyum=malayalamMovies[16];
		System.out.println(ayyappanumKoshiyum);
		String kaathal=malayalamMovies[17];
		System.out.println(kaathal);
		String bhramam=malayalamMovies[18];
		System.out.println(bhramam);
		String saras=malayalamMovies[19];
		System.out.println(saras);
		String helen=malayalamMovies[20];
		System.out.println(helen);
		String unda=malayalamMovies[21];
		System.out.println(unda);
		String virus=malayalamMovies[22];
		System.out.println(virus);
		String garudan=malayalamMovies[23];
		System.out.println(garudan);
		String malik=malayalamMovies[24];
		System.out.println(malik);
		String greatIndianKitchen=malayalamMovies[25];
		System.out.println(greatIndianKitchen);
		String androidKunjappan=malayalamMovies[26];
		System.out.println(androidKunjappan);
		String uyare=malayalamMovies[27];
		System.out.println(uyare);
		String thondimuthalum=malayalamMovies[28];
		System.out.println(thondimuthalum);
		String takeOff=malayalamMovies[29];
		System.out.println(takeOff);

		

		String shershaah=hindiMovies[0];
		System.out.println(shershaah);
		String sardarUdham=hindiMovies[1];
		System.out.println(sardarUdham);
		String majaMa=hindiMovies[2];
		System.out.println(majaMa);
		String tikuWedsSheru=hindiMovies[3];
		System.out.println(tikuWedsSheru);
		String sharmajeeKiBeti=hindiMovies[4];
		System.out.println(sharmajeeKiBeti);
		String aeWatanMereWatan=hindiMovies[5];
		System.out.println(aeWatanMereWatan);
		String runway34=hindiMovies[6];
		System.out.println(runway34);
		String jugJuggJeeyo=hindiMovies[7];
		System.out.println(jugJuggJeeyo);
		String yehJawaaniHaiDeewani=hindiMovies[8];
		System.out.println(yehJawaaniHaiDeewani);
		String barfi=hindiMovies[9];
		System.out.println(barfi);
		String raazi=hindiMovies[10];
		System.out.println(raazi);
		String theLunchbox=hindiMovies[11];
		System.out.println(theLunchbox);
		String tumbbad=hindiMovies[12];
		System.out.println(tumbbad);
		String stree=hindiMovies[13];
		System.out.println(stree);
		String section375=hindiMovies[14];
		System.out.println(section375);
		String hindiMedium=hindiMovies[15];
		System.out.println(hindiMedium);
		String aashiqui2=hindiMovies[16];
		System.out.println(aashiqui2);
		String rajaHindustani=hindiMovies[17];
		System.out.println(rajaHindustani);
		String humDilDeChukeSanam=hindiMovies[18];
		System.out.println(humDilDeChukeSanam);
		String ajabPremKiGhazabKahani=hindiMovies[19];
		System.out.println(ajabPremKiGhazabKahani);
		String bachchhanPaandey=hindiMovies[20];
		System.out.println(bachchhanPaandey);
		String unpaused=hindiMovies[21];
		System.out.println(unpaused);
		String toofaan=hindiMovies[22];
		System.out.println(toofaan);
		String gehraiyaan=hindiMovies[23];
		System.out.println(gehraiyaan);
		String bhootPartOne=hindiMovies[24];
		System.out.println(bhootPartOne);
		String fan=hindiMovies[25];
		System.out.println(fan);
		String satyamevaJayate=hindiMovies[26];
		System.out.println(satyamevaJayate);
		String coolieNo1=hindiMovies[27];
		System.out.println(coolieNo1);
		String dilBechara=hindiMovies[28];
		System.out.println(dilBechara);
		String goodNewwz=hindiMovies[29];
		System.out.println(goodNewwz);

		
		String shawshank=englishMovies[0];
		System.out.println(shawshank);
		String lotr1=englishMovies[1];
		System.out.println(lotr1);
		String lotr2=englishMovies[2];
		System.out.println(lotr2);
		String lotr3=englishMovies[3];
		System.out.println(lotr3);
		String matrix=englishMovies[4];
		System.out.println(matrix);
		String inception=englishMovies[5];
		System.out.println(inception);
		String interstellar=englishMovies[6];
		System.out.println(interstellar);
		String gladiator=englishMovies[7];
		System.out.println(gladiator);
		String darkKnight=englishMovies[8];
		System.out.println(darkKnight);
		String titanic=englishMovies[9];
		System.out.println(titanic);
		String forrestGump=englishMovies[10];
		System.out.println(forrestGump);
		String prestige=englishMovies[11];
		System.out.println(prestige);
		String arrival=englishMovies[12];
		System.out.println(arrival);
		String silenceOfTheLambs=englishMovies[13];
		System.out.println(silenceOfTheLambs);
		String socialNetwork=englishMovies[14];
		System.out.println(socialNetwork);
		String madMax=englishMovies[15];
		System.out.println(madMax);
		String wolfOfWallStreet=englishMovies[16];
		System.out.println(wolfOfWallStreet);
		String quietPlace=englishMovies[17];
		System.out.println(quietPlace);
		String tomorrowWar=englishMovies[18];
		System.out.println(tomorrowWar);
		String missionImpossible=englishMovies[19];
		System.out.println(missionImpossible);
		String noTimeToDie=englishMovies[20];
		System.out.println(noTimeToDie);
		String casinoRoyale=englishMovies[21];
		System.out.println(casinoRoyale);
		String beekeeper=englishMovies[22];
		System.out.println(beekeeper);
		String bigLebowski=englishMovies[23];
		System.out.println(bigLebowski);
		String laLaLand=englishMovies[24];
		System.out.println(laLaLand);
		String readyPlayerOne=englishMovies[25];
		System.out.println(readyPlayerOne);
		String collateral=englishMovies[26];
		System.out.println(collateral);
		String fargo=englishMovies[27];
		System.out.println(fargo);
		String redWhiteRoyalBlue=englishMovies[28];
		System.out.println(redWhiteRoyalBlue);
		String upgraded=englishMovies[29];
		System.out.println(upgraded);

	
	}
}