class JioHotStar
{
	public static void main(String[] star)
	{
		String comedyMovies[]={"Jathi Ratnalu","F2: Fun and Frustration","F3: Fun and Frustration","DJ Tillu","Tillu Square","Brochevarevarura","Venky","Dhee","Ready","Race Gurram","Nuvvu Naaku Nachav","Namo Venkatesa","Adhurs","King","Kick","Julayi","Sudigadu","Bhale Bhale Magadivoy","Pelli Choopulu","Ee Nagaraniki Emaindi","Ala Vaikunthapurramuloo","Bendu Apparao R.M.P","Allari","Kitakitalu","Sudigaadu 2","Hello Brother","Manmadhudu","Dubai Seenu","Chantabbai","Jamba Lakidi Pamba"};
		String thrillerMovies[]={"Drishyam","Ratsasan","Andhadhun","Kahaani","Evaru","Hit: The First Case","Hit: The Second Case","Vikram Vedha","The Family Man","Shutter Island","Gone Girl","Se7en","The Silence of the Lambs","Prisoners","Zodiac","The Girl with the Dragon Tattoo","A Wednesday","Ugly","Talvar","Anjaam Pathiraa","Joseph","Kavaludaari","Game Over","Badla","Talaash","Memories","The Invisible Guest","Knives Out","The Sixth Sense","No Country for Old Men"};
		String dramas[]={"Forrest Gump","The Shawshank Redemption","Green Book","The Pursuit of Happyness","A Beautiful Mind","Titanic","The Green Mile","12 Years a Slave","Parasite","Whiplash","The Social Network","Marriage Story","Manchester by the Sea","Taare Zameen Par","Dangal","Sita Ramam","96","Kumbalangi Nights","Joji","Super Deluxe","The Lunchbox","Barfi!","Udaan","Masaan","Thappad","Aruvi","C/o Kancharapalem","Uyare","The Father","Million Dollar Baby"};
		String crimeMovies[]={"The Godfather","The Godfather Part II","Goodfellas","The Departed","Scarface","Pulp Fiction","Se7en","The Usual Suspects","Heat","Casino","City of God","No Country for Old Men","Zodiac","Donnie Brasco","American Gangster","A Wednesday","Special 26","Gangs of Wasseypur","Black Friday","Talvar","Drishyam","Vikram Vedha","Ratsasan","Kaithi","Anjaam Pathiraa","Joseph","Kavaludaari","Memories","The Irishman","Prisoners"};
		String scienceFictionMovies[]={"Interstellar","Inception","The Matrix","The Matrix Reloaded","The Matrix Revolutions","Avatar","Avatar: The Way of Water","The Terminator","Terminator 2: Judgment Day","Blade Runner 2049","Arrival","Gravity","The Martian","Edge of Tomorrow","A Quiet Place","Ready Player One","Dune","Tenet","E.T. the Extra-Terrestrial","Jurassic Park","Jurassic World","PK","Enthiran","2.0","24","Aditya 369","Eega","Koi... Mil Gaya","War of the Worlds","I Am Legend"};
		String adventureMovies[]={"Indiana Jones and the Raiders of the Lost Ark","Indiana Jones and the Last Crusade","The Lord of the Rings: The Fellowship of the Ring","The Lord of the Rings: The Two Towers","The Lord of the Rings: The Return of the King","The Hobbit: An Unexpected Journey","Pirates of the Caribbean: The Curse of the Black Pearl","Pirates of the Caribbean: Dead Man's Chest","Jurassic Park","Jurassic World","The Mummy","The Revenant","Life of Pi","Cast Away","Into the Wild","Jumanji: Welcome to the Jungle","Jumanji: The Next Level","Mad Max: Fury Road","The Chronicles of Narnia: The Lion, the Witch and the Wardrobe","King Kong","Baahubali: The Beginning","Baahubali: The Conclusion","RRR","Magadheera","Eega","Kantara","Thugs of Hindostan","The Jungle Book","Everest","The Secret Life of Walter Mitty"};
		
		String jathiRatnalu=comedyMovies[0];
		System.out.println(jathiRatnalu);
		String f2Comedy=comedyMovies[1];
		System.out.println(f2Comedy);
		String f3Comedy=comedyMovies[2];
		System.out.println(f3Comedy);
		String djTillu=comedyMovies[3];
		System.out.println(djTillu);
		String tilluSquare=comedyMovies[4];
		System.out.println(tilluSquare);
		String brochevarevarura=comedyMovies[5];
		System.out.println(brochevarevarura);
		String venky=comedyMovies[6];
		System.out.println(venky);
		String dhee=comedyMovies[7];
		System.out.println(dhee);
		String ready=comedyMovies[8];
		System.out.println(ready);
		String raceGurram=comedyMovies[9];
		System.out.println(raceGurram);
		String nuvvuNaakuNachav=comedyMovies[10];
		System.out.println(nuvvuNaakuNachav);
		String namoVenkatesa=comedyMovies[11];
		System.out.println(namoVenkatesa);
		String adhurs=comedyMovies[12];
		System.out.println(adhurs);
		String king=comedyMovies[13];
		System.out.println(king);
		String kick=comedyMovies[14];
		System.out.println(kick);
		String julayi=comedyMovies[15];
		System.out.println(julayi);
		String sudigadu=comedyMovies[16];
		System.out.println(sudigadu);
		String bhaleBhaleMagadivoy=comedyMovies[17];
		System.out.println(bhaleBhaleMagadivoy);
		String pelliChoopulu=comedyMovies[18];
		System.out.println(pelliChoopulu);
		String eeNagaranikiEmaindi=comedyMovies[19];
		System.out.println(eeNagaranikiEmaindi);
		String alaVaikunthapurramuloo=comedyMovies[20];
		System.out.println(alaVaikunthapurramuloo);
		String benduApparao=comedyMovies[21];
		System.out.println(benduApparao);
		String allari=comedyMovies[22];
		System.out.println(allari);
		String kitakitalu=comedyMovies[23];
		System.out.println(kitakitalu);
		String sudigaadu2=comedyMovies[24];
		System.out.println(sudigaadu2);
		String helloBrother=comedyMovies[25];
		System.out.println(helloBrother);
		String manmadhudu=comedyMovies[26];
		System.out.println(manmadhudu);
		String dubaiSeenu=comedyMovies[27];
		System.out.println(dubaiSeenu);
		String chantabbai=comedyMovies[28];
		System.out.println(chantabbai);
		String jambaLakidiPamba=comedyMovies[29];
		System.out.println(jambaLakidiPamba);

		

		String drishyamThriller=thrillerMovies[0];
		System.out.println(drishyamThriller);
		String ratsasan=thrillerMovies[1];
		System.out.println(ratsasan);
		String andhadhun=thrillerMovies[2];
		System.out.println(andhadhun);
		String kahaani=thrillerMovies[3];
		System.out.println(kahaani);
		String evaruThriller=thrillerMovies[4];
		System.out.println(evaruThriller);
		String hitFirst=thrillerMovies[5];
		System.out.println(hitFirst);
		String hitSecond=thrillerMovies[6];
		System.out.println(hitSecond);
		String vikramVedhaThriller=thrillerMovies[7];
		System.out.println(vikramVedhaThriller);
		String familyMan=thrillerMovies[8];
		System.out.println(familyMan);
		String shutterIslandThriller=thrillerMovies[9];
		System.out.println(shutterIslandThriller);
		String goneGirl=thrillerMovies[10];
		System.out.println(goneGirl);
		String se7en=thrillerMovies[11];
		System.out.println(se7en);
		String silenceOfLambs=thrillerMovies[12];
		System.out.println(silenceOfLambs);
		String prisoners=thrillerMovies[13];
		System.out.println(prisoners);
		String zodiac=thrillerMovies[14];
		System.out.println(zodiac);
		String girlWithDragonTattoo=thrillerMovies[15];
		System.out.println(girlWithDragonTattoo);
		String aWednesday=thrillerMovies[16];
		System.out.println(aWednesday);
		String ugly=thrillerMovies[17];
		System.out.println(ugly);
		String talvar=thrillerMovies[18];
		System.out.println(talvar);
		String anjaamPathiraa=thrillerMovies[19];
		System.out.println(anjaamPathiraa);
		String josephThriller=thrillerMovies[20];
		System.out.println(josephThriller);
		String kavaludaari=thrillerMovies[21];
		System.out.println(kavaludaari);
		String gameOver=thrillerMovies[22];
		System.out.println(gameOver);
		String badla=thrillerMovies[23];
		System.out.println(badla);
		String talaash=thrillerMovies[24];
		System.out.println(talaash);
		String memories=thrillerMovies[25];
		System.out.println(memories);
		String invisibleGuest=thrillerMovies[26];
		System.out.println(invisibleGuest);
		String knivesOut=thrillerMovies[27];
		System.out.println(knivesOut);
		String sixthSense=thrillerMovies[28];
		System.out.println(sixthSense);
		String noCountry=thrillerMovies[29];
		System.out.println(noCountry);

		

		String forrestGump=dramas[0];
		System.out.println(forrestGump);
		String shawshankRedemption=dramas[1];
		System.out.println(shawshankRedemption);
		String greenBook=dramas[2];
		System.out.println(greenBook);
		String pursuitOfHappyness=dramas[3];
		System.out.println(pursuitOfHappyness);
		String beautifulMind=dramas[4];
		System.out.println(beautifulMind);
		String titanicDrama=dramas[5];
		System.out.println(titanicDrama);
		String greenMile=dramas[6];
		System.out.println(greenMile);
		String twelveYearsASlave=dramas[7];
		System.out.println(twelveYearsASlave);
		String parasite=dramas[8];
		System.out.println(parasite);
		String whiplash=dramas[9];
		System.out.println(whiplash);
		String socialNetworkDrama=dramas[10];
		System.out.println(socialNetworkDrama);
		String marriageStory=dramas[11];
		System.out.println(marriageStory);
		String manchesterByTheSea=dramas[12];
		System.out.println(manchesterByTheSea);
		String taareZameenPar=dramas[13];
		System.out.println(taareZameenPar);
		String dangalDrama=dramas[14];
		System.out.println(dangalDrama);
		String sitaRamam=dramas[15];
		System.out.println(sitaRamam);
		String ninetySixDrama=dramas[16];
		System.out.println(ninetySixDrama);
		String kumbalangiNightsDrama=dramas[17];
		System.out.println(kumbalangiNightsDrama);
		String jojiDrama=dramas[18];
		System.out.println(jojiDrama);
		String superDeluxe=dramas[19];
		System.out.println(superDeluxe);
		String lunchbox=dramas[20];
		System.out.println(lunchbox);
		String barfiDrama=dramas[21];
		System.out.println(barfiDrama);
		String udaan=dramas[22];
		System.out.println(udaan);
		String masaan=dramas[23];
		System.out.println(masaan);
		String thappad=dramas[24];
		System.out.println(thappad);
		String aruvi=dramas[25];
		System.out.println(aruvi);
		String coKancharapalem=dramas[26];
		System.out.println(coKancharapalem);
		String uyareDrama=dramas[27];
		System.out.println(uyareDrama);
		String father=dramas[28];
		System.out.println(father);
		String millionDollarBaby=dramas[29];
		System.out.println(millionDollarBaby);

		

		String godfather=crimeMovies[0];
		System.out.println(godfather);
		String godfather2=crimeMovies[1];
		System.out.println(godfather2);
		String goodfellas=crimeMovies[2];
		System.out.println(goodfellas);
		String departed=crimeMovies[3];
		System.out.println(departed);
		String scarface=crimeMovies[4];
		System.out.println(scarface);
		String pulpFiction=crimeMovies[5];
		System.out.println(pulpFiction);
		String se7enCrime=crimeMovies[6];
		System.out.println(se7enCrime);
		String usualSuspects=crimeMovies[7];
		System.out.println(usualSuspects);
		String heat=crimeMovies[8];
		System.out.println(heat);
		String casinoCrime=crimeMovies[9];
		System.out.println(casinoCrime);
		String cityOfGod=crimeMovies[10];
		System.out.println(cityOfGod);
		String noCountryCrime=crimeMovies[11];
		System.out.println(noCountryCrime);
		String zodiacCrime=crimeMovies[12];
		System.out.println(zodiacCrime);
		String donnieBrasco=crimeMovies[13];
		System.out.println(donnieBrasco);
		String americanGangster=crimeMovies[14];
		System.out.println(americanGangster);
		String aWednesdayCrime=crimeMovies[15];
		System.out.println(aWednesdayCrime);
		String special26=crimeMovies[16];
		System.out.println(special26);
		String gangsOfWasseypur=crimeMovies[17];
		System.out.println(gangsOfWasseypur);
		String blackFriday=crimeMovies[18];
		System.out.println(blackFriday);
		String talvarCrime=crimeMovies[19];
		System.out.println(talvarCrime);
		String drishyamCrime=crimeMovies[20];
		System.out.println(drishyamCrime);
		String vikramVedhaCrime=crimeMovies[21];
		System.out.println(vikramVedhaCrime);
		String ratsasanCrime=crimeMovies[22];
		System.out.println(ratsasanCrime);
		String kaithi=crimeMovies[23];
		System.out.println(kaithi);
		String anjaamPathiraaCrime=crimeMovies[24];
		System.out.println(anjaamPathiraaCrime);
		String josephCrime=crimeMovies[25];
		System.out.println(josephCrime);
		String kavaludaariCrime=crimeMovies[26];
		System.out.println(kavaludaariCrime);
		String memoriesCrime=crimeMovies[27];
		System.out.println(memoriesCrime);
		String irishman=crimeMovies[28];
		System.out.println(irishman);
		String prisonersCrime=crimeMovies[29];
		System.out.println(prisonersCrime);

		

		String interstellar=scienceFictionMovies[0];
		System.out.println(interstellar);
		String inception=scienceFictionMovies[1];
		System.out.println(inception);
		String matrix=scienceFictionMovies[2];
		System.out.println(matrix);
		String matrixReloaded=scienceFictionMovies[3];
		System.out.println(matrixReloaded);
		String matrixRevolutions=scienceFictionMovies[4];
		System.out.println(matrixRevolutions);
		String avatar=scienceFictionMovies[5];
		System.out.println(avatar);
		String avatarWayOfWater=scienceFictionMovies[6];
		System.out.println(avatarWayOfWater);
		String terminator=scienceFictionMovies[7];
		System.out.println(terminator);
		String terminator2=scienceFictionMovies[8];
		System.out.println(terminator2);
		String bladeRunner2049=scienceFictionMovies[9];
		System.out.println(bladeRunner2049);
		String arrivalSciFi=scienceFictionMovies[10];
		System.out.println(arrivalSciFi);
		String gravity=scienceFictionMovies[11];
		System.out.println(gravity);
		String martian=scienceFictionMovies[12];
		System.out.println(martian);
		String edgeOfTomorrow=scienceFictionMovies[13];
		System.out.println(edgeOfTomorrow);
		String quietPlaceSciFi=scienceFictionMovies[14];
		System.out.println(quietPlaceSciFi);
		String readyPlayerOneSciFi=scienceFictionMovies[15];
		System.out.println(readyPlayerOneSciFi);
		String dune=scienceFictionMovies[16];
		System.out.println(dune);
		String tenet=scienceFictionMovies[17];
		System.out.println(tenet);
		String et=scienceFictionMovies[18];
		System.out.println(et);
		String jurassicPark=scienceFictionMovies[19];
		System.out.println(jurassicPark);
		String jurassicWorld=scienceFictionMovies[20];
		System.out.println(jurassicWorld);
		String pkSciFi=scienceFictionMovies[21];
		System.out.println(pkSciFi);
		String enthiran=scienceFictionMovies[22];
		System.out.println(enthiran);
		String twoPointZero=scienceFictionMovies[23];
		System.out.println(twoPointZero);
		String twentyFour=scienceFictionMovies[24];
		System.out.println(twentyFour);
		String aditya369=scienceFictionMovies[25];
		System.out.println(aditya369);
		String eegaSciFi=scienceFictionMovies[26];
		System.out.println(eegaSciFi);
		String koiMilGaya=scienceFictionMovies[27];
		System.out.println(koiMilGaya);
		String warOfTheWorlds=scienceFictionMovies[28];
		System.out.println(warOfTheWorlds);
		String iAmLegend=scienceFictionMovies[29];
		System.out.println(iAmLegend);

		
				
		String raidersOfLostArk=adventureMovies[0];
		System.out.println(raidersOfLostArk);
		String lastCrusade=adventureMovies[1];
		System.out.println(lastCrusade);
		String lotrFellowship=adventureMovies[2];
		System.out.println(lotrFellowship);
		String lotrTwoTowers=adventureMovies[3];
		System.out.println(lotrTwoTowers);
		String lotrReturnKing=adventureMovies[4];
		System.out.println(lotrReturnKing);
		String hobbitUnexpectedJourney=adventureMovies[5];
		System.out.println(hobbitUnexpectedJourney);
		String piratesBlackPearl=adventureMovies[6];
		System.out.println(piratesBlackPearl);
		String piratesDeadManChest=adventureMovies[7];
		System.out.println(piratesDeadManChest);
		String jurassicParkAdventure=adventureMovies[8];
		System.out.println(jurassicParkAdventure);
		String jurassicWorldAdventure=adventureMovies[9];
		System.out.println(jurassicWorldAdventure);
		String mummy=adventureMovies[10];
		System.out.println(mummy);
		String revenant=adventureMovies[11];
		System.out.println(revenant);
		String lifeOfPi=adventureMovies[12];
		System.out.println(lifeOfPi);
		String castAway=adventureMovies[13];
		System.out.println(castAway);
		String intoTheWild=adventureMovies[14];
		System.out.println(intoTheWild);
		String jumanjiWelcome=adventureMovies[15];
		System.out.println(jumanjiWelcome);
		String jumanjiNextLevel=adventureMovies[16];
		System.out.println(jumanjiNextLevel);
		String madMaxFuryRoad=adventureMovies[17];
		System.out.println(madMaxFuryRoad);
		String narnia=adventureMovies[18];
		System.out.println(narnia);
		String kingKong=adventureMovies[19];
		System.out.println(kingKong);
		String baahubaliBeginning=adventureMovies[20];
		System.out.println(baahubaliBeginning);
		String baahubaliConclusion=adventureMovies[21];
		System.out.println(baahubaliConclusion);
		String rrrAdventure=adventureMovies[22];
		System.out.println(rrrAdventure);
		String magadheera=adventureMovies[23];
		System.out.println(magadheera);
		String eegaAdventure=adventureMovies[24];
		System.out.println(eegaAdventure);
		String kantaraAdventure=adventureMovies[25];
		System.out.println(kantaraAdventure);
		String thugsOfHindostan=adventureMovies[26];
		System.out.println(thugsOfHindostan);
		String jungleBook=adventureMovies[27];
		System.out.println(jungleBook);
		String everest=adventureMovies[28];
		System.out.println(everest);
		String secretLifeWalterMitty=adventureMovies[29];
		System.out.println(secretLifeWalterMitty);
		
		
	}	
}