class SonyLiv
{
	public static void main(String[] star)
	{
		String teluguSeries[]={"Loser","Locked","Meka Suri","Recce","Maa Neella Tank","Oka Chinna Family Story","Prema Entha Madhuram","Kalyana Vaibhogam","No.1 Kodalu","Suryakantham","Trinayani","Krishna Tulasi","Radhamma Kuthuru","Hitler Gari Pellam","Devathalara Deevinchandi","Inti Guttu","Kalyana Vaibhogam (2022)","Mutyala Muggu","Varudhini Parinayam","Mana Ambedkar","Muddha Mandaram","Mangamma Gari Manavaralu","Gundamma Katha (Series)","Ninne Pelladatha (Zee5)","America Ammayi","Adhikar","Ammayi Garu","Ramaraju","Chadarangam","Vyavastha"};
		String kannadaSeries[]={"Gattimela","Jothe Jotheyali","Yaare Nee Mohini","Kamali","Paaru","Naagini 2","Brahmagantu","Subbalakshmi Samsara","Sathya","Kinnari","Radha Ramana","Ganga","Mahadevi","Mangala Gowri Maduve","Nagamandala","Arundhati","Seetha Vallabha","Kaveri","Krishna Rukmini","Anuroopa","Nigooda Ratri","Edheyo","Hoo Male","Mahanati","Anjali","Sose Tanda Sowbhagya","Putmalli","Jodi Hakki","Shubhavivaha","Bandhana"};
		String tamilSeries[]={"Sembaruthi","Yaaradi Nee Mohini","Poove Poochoodava","Sathya","Oru Oorula Oru Rajakumari","Rettai Roja","Devathaiyai Kanden","Neethane Enthan Ponvasantham","Peranbu","Rajamagal","Maari","Chithiram Pesuthadi","Thirumathi Hitler","Ninaithale Inikkum","Kannathil Muthamittal (Series)","Amudhavum Annalakshmiyum","Vidhya No.1","Karthigai Deepam","Anna","Sandhya Raagam","Meenakshi Ponnunga","Idhayam","Anbe Sivam (Series)","Suryavamsam (Series)","Veera","Pudhu Pudhu Arthangal","Nenjathai Killathe (Series)","Thavamai Thavamirundhu (Series)","Thalayanai Pookal","Uyire"};
		String malayalamSeries[]={"Chembarathi","Neeyum Njanum","Kaiyethum Doorath","Mrs Hitler","Kudumbashree Sharada","Mizhi Randilum","Manam Pole Mangalyam","Sathya Enna Penkutty","Sumangali Bhava","Pookalam Varavayi","Suryakanthi","Ayalathe Sundari","Moonnumani","Mangalyam","Swathi Nakshatram Chothi","Pranayavarnangal","Bharya","Bandhanam","Makkal","Nokketha Doorathu","Shyamambaram","Snehakoodu","Karthika Deepam (Malayalam)","Ammayariyathe","Nandanam","Indira","Arayannangalude Veedu","Kudumbavilakku","Ente Maathavu","Seetha Kalyanam"};
		String englishSeries[]={"The Broken News","Abhay","Sunflower","Kaafir","Rangbaaz","Rangbaaz: Darr Ki Rajneeti","State of Siege: 26/11","State of Siege: Temple Attack","Poison","Poison 2","Duranga","Duranga 2","Code M","Code M 2","Karenjit Kaur","The Final Call","Lalbazaar","Bombers","Naxalbari","Black Widows","Bloody Brothers","Tripling","Never Kiss Your Best Friend","Fittrat","Bicchoo Ka Khel","Jeet Ki Zid","REJCTX","High Priestess","The Married Woman","Smoke"};
		String hindiSeries[]={"Abhay","Rangbaaz","Rangbaaz: Darr Ki Rajneeti","Sunflower","Kaafir","State of Siege: 26/11","State of Siege: Temple Attack","Poison","Poison 2","Duranga","Duranga 2","Code M","Code M 2","Karenjit Kaur","The Final Call","Lalbazaar","Bombers","Naxalbari","Black Widows","Bloody Brothers","Tripling","Never Kiss Your Best Friend","Fittrat","Bicchoo Ka Khel","Jeet Ki Zid","REJCTX","High Priestess","The Married Woman","Smoke","Taj: Divided by Blood"};
		
		String loser=teluguSeries[0];
		System.out.println(loser);
		String locked=teluguSeries[1];
		System.out.println(locked);
		String mekaSuri=teluguSeries[2];
		System.out.println(mekaSuri);
		String recce=teluguSeries[3];
		System.out.println(recce);
		String maaNeellaTank=teluguSeries[4];
		System.out.println(maaNeellaTank);
		String okaChinnaFamilyStory=teluguSeries[5];
		System.out.println(okaChinnaFamilyStory);
		String premaEnthaMadhuram=teluguSeries[6];
		System.out.println(premaEnthaMadhuram);
		String kalyanaVaibhogam=teluguSeries[7];
		System.out.println(kalyanaVaibhogam);
		String no1Kodalu=teluguSeries[8];
		System.out.println(no1Kodalu);
		String suryakantham=teluguSeries[9];
		System.out.println(suryakantham);
		String trinayani=teluguSeries[10];
		System.out.println(trinayani);
		String krishnaTulasi=teluguSeries[11];
		System.out.println(krishnaTulasi);
		String radhammaKuthuru=teluguSeries[12];
		System.out.println(radhammaKuthuru);
		String hitlerGariPellam=teluguSeries[13];
		System.out.println(hitlerGariPellam);
		String devathalaraDeevinchandi=teluguSeries[14];
		System.out.println(devathalaraDeevinchandi);
		String intiGuttu=teluguSeries[15];
		System.out.println(intiGuttu);
		String kalyanaVaibhogam2022=teluguSeries[16];
		System.out.println(kalyanaVaibhogam2022);
		String mutyalaMuggu=teluguSeries[17];
		System.out.println(mutyalaMuggu);
		String varudhiniParinayam=teluguSeries[18];
		System.out.println(varudhiniParinayam);
		String manaAmbedkar=teluguSeries[19];
		System.out.println(manaAmbedkar);
		String muddhamandaram=teluguSeries[20];
		System.out.println(muddhamandaram);
		String mangammaGariManavaralu=teluguSeries[21];
		System.out.println(mangammaGariManavaralu);
		String gundammaKathaSeries=teluguSeries[22];
		System.out.println(gundammaKathaSeries);
		String ninnePelladathaZee5=teluguSeries[23];
		System.out.println(ninnePelladathaZee5);
		String americaAmmayi=teluguSeries[24];
		System.out.println(americaAmmayi);
		String adhikar=teluguSeries[25];
		System.out.println(adhikar);
		String ammayiGaru=teluguSeries[26];
		System.out.println(ammayiGaru);
		String ramaraju=teluguSeries[27];
		System.out.println(ramaraju);
		String chadarangam=teluguSeries[28];
		System.out.println(chadarangam);
		String vyavastha=teluguSeries[29];
		System.out.println(vyavastha);
				
		
		String gattimela=kannadaSeries[0];
		System.out.println(gattimela);
		String jotheJotheyali=kannadaSeries[1];
		System.out.println(jotheJotheyali);
		String yaareNeeMohini=kannadaSeries[2];
		System.out.println(yaareNeeMohini);
		String kamali=kannadaSeries[3];
		System.out.println(kamali);
		String paaru=kannadaSeries[4];
		System.out.println(paaru);
		String naagini2=kannadaSeries[5];
		System.out.println(naagini2);
		String brahmagantu=kannadaSeries[6];
		System.out.println(brahmagantu);
		String subbalakshmiSamsara=kannadaSeries[7];
		System.out.println(subbalakshmiSamsara);
		String sathya=kannadaSeries[8];
		System.out.println(sathya);
		String kinnari=kannadaSeries[9];
		System.out.println(kinnari);
		String radhaRamana=kannadaSeries[10];
		System.out.println(radhaRamana);
		String ganga=kannadaSeries[11];
		System.out.println(ganga);
		String mahadevi=kannadaSeries[12];
		System.out.println(mahadevi);
		String mangalaGowriMaduve=kannadaSeries[13];
		System.out.println(mangalaGowriMaduve);
		String nagamandala=kannadaSeries[14];
		System.out.println(nagamandala);
		String arundhati=kannadaSeries[15];
		System.out.println(arundhati);
		String seethaVallabha=kannadaSeries[16];
		System.out.println(seethaVallabha);
		String kaveri=kannadaSeries[17];
		System.out.println(kaveri);
		String krishnaRukmini=kannadaSeries[18];
		System.out.println(krishnaRukmini);
		String anuroopa=kannadaSeries[19];
		System.out.println(anuroopa);
		String nigoodaRatri=kannadaSeries[20];
		System.out.println(nigoodaRatri);
		String edheyo=kannadaSeries[21];
		System.out.println(edheyo);
		String hooMale=kannadaSeries[22];
		System.out.println(hooMale);
		String mahanati=kannadaSeries[23];
		System.out.println(mahanati);
		String anjali=kannadaSeries[24];
		System.out.println(anjali);
		String soseTandaSowbhagya=kannadaSeries[25];
		System.out.println(soseTandaSowbhagya);
		String putmalli=kannadaSeries[26];
		System.out.println(putmalli);
		String jodiHakki=kannadaSeries[27];
		System.out.println(jodiHakki);
		String shubhavivaha=kannadaSeries[28];
		System.out.println(shubhavivaha);
		String bandhana=kannadaSeries[29];
		System.out.println(bandhana);

		
		String sembaruthi=tamilSeries[0];
		System.out.println(sembaruthi);
		String yaaradiNeeMohini=tamilSeries[1];
		System.out.println(yaaradiNeeMohini);
		String poovePoochoodava=tamilSeries[2];
		System.out.println(poovePoochoodava);
		String sathyaTamil=tamilSeries[3];
		System.out.println(sathyaTamil);
		String oruOorulaOruRajakumari=tamilSeries[4];
		System.out.println(oruOorulaOruRajakumari);
		String rettaiRoja=tamilSeries[5];
		System.out.println(rettaiRoja);
		String devathaiyaiKanden=tamilSeries[6];
		System.out.println(devathaiyaiKanden);
		String neethaneEnthanPonvasantham=tamilSeries[7];
		System.out.println(neethaneEnthanPonvasantham);
		String peranbu=tamilSeries[8];
		System.out.println(peranbu);
		String rajamagal=tamilSeries[9];
		System.out.println(rajamagal);
		String maariSeries=tamilSeries[10];
		System.out.println(maariSeries);
		String chithiramPesuthadi=tamilSeries[11];
		System.out.println(chithiramPesuthadi);
		String thirumathiHitler=tamilSeries[12];
		System.out.println(thirumathiHitler);
		String ninaithaleInikkum=tamilSeries[13];
		System.out.println(ninaithaleInikkum);
		String kannathilMuthamittal=tamilSeries[14];
		System.out.println(kannathilMuthamittal);
		String amudhavumAnnalakshmiyum=tamilSeries[15];
		System.out.println(amudhavumAnnalakshmiyum);
		String vidhyaNo1=tamilSeries[16];
		System.out.println(vidhyaNo1);
		String karthigaiDeepam=tamilSeries[17];
		System.out.println(karthigaiDeepam);
		String anna=tamilSeries[18];
		System.out.println(anna);
		String sandhyaRaagam=tamilSeries[19];
		System.out.println(sandhyaRaagam);
		String meenakshiPonnunga=tamilSeries[20];
		System.out.println(meenakshiPonnunga);
		String idhayam=tamilSeries[21];
		System.out.println(idhayam);
		String anbeSivamSeries=tamilSeries[22];
		System.out.println(anbeSivamSeries);
		String suryavamsamSeries=tamilSeries[23];
		System.out.println(suryavamsamSeries);
		String veera=tamilSeries[24];
		System.out.println(veera);
		String pudhuPudhuArthangal=tamilSeries[25];
		System.out.println(pudhuPudhuArthangal);
		String nenjathaiKillathe=tamilSeries[26];
		System.out.println(nenjathaiKillathe);
		String thavamaiThavamirundhu=tamilSeries[27];
		System.out.println(thavamaiThavamirundhu);
		String thalayanaiPookal=tamilSeries[28];
		System.out.println(thalayanaiPookal);
		String uyire=tamilSeries[29];
		System.out.println(uyire);

		

		String chembarathi=malayalamSeries[0];
		System.out.println(chembarathi);
		String neeyumNjanum=malayalamSeries[1];
		System.out.println(neeyumNjanum);
		String kaiyethumDoorath=malayalamSeries[2];
		System.out.println(kaiyethumDoorath);
		String mrsHitler=malayalamSeries[3];
		System.out.println(mrsHitler);
		String kudumbashreeSharada=malayalamSeries[4];
		System.out.println(kudumbashreeSharada);
		String mizhiRandilum=malayalamSeries[5];
		System.out.println(mizhiRandilum);
		String manamPoleMangalyam=malayalamSeries[6];
		System.out.println(manamPoleMangalyam);
		String sathyaEnnaPenkutty=malayalamSeries[7];
		System.out.println(sathyaEnnaPenkutty);
		String sumangaliBhava=malayalamSeries[8];
		System.out.println(sumangaliBhava);
		String pookalamVaravayi=malayalamSeries[9];
		System.out.println(pookalamVaravayi);
		String suryakanthi=malayalamSeries[10];
		System.out.println(suryakanthi);
		String ayalatheSundari=malayalamSeries[11];
		System.out.println(ayalatheSundari);
		String moonnumani=malayalamSeries[12];
		System.out.println(moonnumani);
		String mangalyam=malayalamSeries[13];
		System.out.println(mangalyam);
		String swathiNakshatramChothi=malayalamSeries[14];
		System.out.println(swathiNakshatramChothi);
		String pranayavarnangal=malayalamSeries[15];
		System.out.println(pranayavarnangal);
		String bharya=malayalamSeries[16];
		System.out.println(bharya);
		String bandhanam=malayalamSeries[17];
		System.out.println(bandhanam);
		String makkal=malayalamSeries[18];
		System.out.println(makkal);
		String nokkethaDoorathu=malayalamSeries[19];
		System.out.println(nokkethaDoorathu);
		String shyamambaram=malayalamSeries[20];
		System.out.println(shyamambaram);
		String snehakoodu=malayalamSeries[21];
		System.out.println(snehakoodu);
		String karthikaDeepamMalayalam=malayalamSeries[22];
		System.out.println(karthikaDeepamMalayalam);
		String ammayariyathe=malayalamSeries[23];
		System.out.println(ammayariyathe);
		String nandanam=malayalamSeries[24];
		System.out.println(nandanam);
		String indira=malayalamSeries[25];
		System.out.println(indira);
		String arayannangaludeVeedu=malayalamSeries[26];
		System.out.println(arayannangaludeVeedu);
		String kudumbavilakku=malayalamSeries[27];
		System.out.println(kudumbavilakku);
		String enteMaathavu=malayalamSeries[28];
		System.out.println(enteMaathavu);
		String seethaKalyanam=malayalamSeries[29];
		System.out.println(seethaKalyanam);

		

		String brokenNews=englishSeries[0];
		System.out.println(brokenNews);
		String abhayEnglish=englishSeries[1];
		System.out.println(abhayEnglish);
		String sunflower=englishSeries[2];
		System.out.println(sunflower);
		String kaafir=englishSeries[3];
		System.out.println(kaafir);
		String rangbaaz=englishSeries[4];
		System.out.println(rangbaaz);
		String rangbaazRajneeti=englishSeries[5];
		System.out.println(rangbaazRajneeti);
		String stateOfSiege2611=englishSeries[6];
		System.out.println(stateOfSiege2611);
		String stateOfSiegeTemple=englishSeries[7];
		System.out.println(stateOfSiegeTemple);
		String poison=englishSeries[8];
		System.out.println(poison);
		String poison2=englishSeries[9];
		System.out.println(poison2);
		String duranga=englishSeries[10];
		System.out.println(duranga);
		String duranga2=englishSeries[11];
		System.out.println(duranga2);
		String codeM=englishSeries[12];
		System.out.println(codeM);
		String codeM2=englishSeries[13];
		System.out.println(codeM2);
		String karenjitKaur=englishSeries[14];
		System.out.println(karenjitKaur);
		String finalCall=englishSeries[15];
		System.out.println(finalCall);
		String lalbazaar=englishSeries[16];
		System.out.println(lalbazaar);
		String bombers=englishSeries[17];
		System.out.println(bombers);
		String naxalbari=englishSeries[18];
		System.out.println(naxalbari);
		String blackWidows=englishSeries[19];
		System.out.println(blackWidows);
		String bloodyBrothers=englishSeries[20];
		System.out.println(bloodyBrothers);
		String tripling=englishSeries[21];
		System.out.println(tripling);
		String neverKiss=englishSeries[22];
		System.out.println(neverKiss);
		String fittrat=englishSeries[23];
		System.out.println(fittrat);
		String bicchooKaKhel=englishSeries[24];
		System.out.println(bicchooKaKhel);
		String jeetKiZid=englishSeries[25];
		System.out.println(jeetKiZid);
		String rejctx=englishSeries[26];
		System.out.println(rejctx);
		String highPriestess=englishSeries[27];
		System.out.println(highPriestess);
		String marriedWoman=englishSeries[28];
		System.out.println(marriedWoman);
		String smoke=englishSeries[29];
		System.out.println(smoke);

	

		String abhayHindi=hindiSeries[0];
		System.out.println(abhayHindi);
		String rangbaazHindi=hindiSeries[1];
		System.out.println(rangbaazHindi);
		String rangbaazDarr=hindiSeries[2];
		System.out.println(rangbaazDarr);
		String sunflowerHindi=hindiSeries[3];
		System.out.println(sunflowerHindi);
		String kaafirHindi=hindiSeries[4];
		System.out.println(kaafirHindi);
		String stateOfSiegeHindi=hindiSeries[5];
		System.out.println(stateOfSiegeHindi);
		String stateOfSiegeTempleHindi=hindiSeries[6];
		System.out.println(stateOfSiegeTempleHindi);
		String poisonHindi=hindiSeries[7];
		System.out.println(poisonHindi);
		String poison2Hindi=hindiSeries[8];
		System.out.println(poison2Hindi);
		String durangaHindi=hindiSeries[9];
		System.out.println(durangaHindi);
		String duranga2Hindi=hindiSeries[10];
		System.out.println(duranga2Hindi);
		String codeMHindi=hindiSeries[11];
		System.out.println(codeMHindi);
		String codeM2Hindi=hindiSeries[12];
		System.out.println(codeM2Hindi);
		String karenjitKaurHindi=hindiSeries[13];
		System.out.println(karenjitKaurHindi);
		String finalCallHindi=hindiSeries[14];
		System.out.println(finalCallHindi);
		String lalbazaarHindi=hindiSeries[15];
		System.out.println(lalbazaarHindi);
		String bombersHindi=hindiSeries[16];
		System.out.println(bombersHindi);
		String naxalbariHindi=hindiSeries[17];
		System.out.println(naxalbariHindi);
		String blackWidowsHindi=hindiSeries[18];
		System.out.println(blackWidowsHindi);
		String bloodyBrothersHindi=hindiSeries[19];
		System.out.println(bloodyBrothersHindi);
		String triplingHindi=hindiSeries[20];
		System.out.println(triplingHindi);
		String neverKissHindi=hindiSeries[21];
		System.out.println(neverKissHindi);
		String fittratHindi=hindiSeries[22];
		System.out.println(fittratHindi);
		String bicchooKaKhelHindi=hindiSeries[23];
		System.out.println(bicchooKaKhelHindi);
		String jeetKiZidHindi=hindiSeries[24];
		System.out.println(jeetKiZidHindi);
		String rejctxHindi=hindiSeries[25];
		System.out.println(rejctxHindi);
		String highPriestessHindi=hindiSeries[26];
		System.out.println(highPriestessHindi);
		String marriedWomanHindi=hindiSeries[27];
		System.out.println(marriedWomanHindi);
		String smokeHindi=hindiSeries[28];
		System.out.println(smokeHindi);
		String tajDividedByBlood=hindiSeries[29];
		System.out.println(tajDividedByBlood);
	}
}